name: CI Pipeline

on:
  pull_request:
    branches:
      - "main"

jobs:
  test-accounts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          pip install black mypy pytest-cov

      - name: Run flake8
        run: poetry run flake8 src

      - name: Run black check
        run: poetry run black --check src

      - name: Run mypy type checks
        run: poetry run mypy src

      - name: Run accounts tests with coverage
        run: poetry run pytest src/tests/test_integration/test_accounts.py --cov=src --cov-report=term --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-accounts
          path: coverage.xml

  test-movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          pip install black mypy pytest-cov

      - name: Run flake8
        run: poetry run flake8 src

      - name: Run black check
        run: poetry run black --check src

      - name: Run mypy type checks
        run: poetry run mypy src

      - name: Run movies tests with coverage
        run: poetry run pytest src/tests/test_integration/test_movies.py --cov=src --cov-report=term --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-movies
          path: coverage.xml

  test-profiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          pip install black mypy pytest-cov

      - name: Run flake8
        run: poetry run flake8 src

      - name: Run black check
        run: poetry run black --check src

      - name: Run mypy type checks
        run: poetry run mypy src

      - name: Run profiles tests with coverage
        run: poetry run pytest src/tests/test_integration/test_profiles.py --cov=src --cov-report=term --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-profiles
          path: coverage.xml

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Docker Compose and wait for completion
        run: docker compose -f docker-compose-tests.yml up --build --abort-on-container-exit --exit-code-from web

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose-tests.yml down
